template:
  default:
    subject_yaml: 【日報】<%%= date %> 部署 名前
    body: |
      ■雑感

      -----------------------------------------------------------------------------------
      ■本日の目標 / 達成状況

      ---------------------------------------------------------------------------------
      ■翌営業日の目標

      ----------------------------------------------------------------------------------
      ■プロフィール
      部署 名前（フロア 内線）
      ・スローガン
      　
      ・カオナビURL
      　
      -----------------------------------------------------------------------------------

      署名
